- type: entity
  id: NukeLatheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: плата ЯдерЛата
  description: Напечатанная плата для создания ЯдерЛата.
  components:
    - type: MachineBoard
      prototype: NukeLathe
      stackRequirements:
        ElectricCompT3: 5
        MechCompT3: 5
        ElectricMotorT3: 3
        Cable: 3
        Glass: 2
        Steel: 2

- type: entity
  id: WeaponLtheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: плата ОружЛата
  description: Напечатанная плата для создания ОружЛата.
  components:
    - type: MachineBoard
      prototype: Weaponlathe
      stackRequirements:
        ElectricCompT3: 5
        MechCompT3: 5
        ElectricMotorT3: 2
        Cable: 3
        Glass: 2
        Steel: 5
